name: Kotlin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.10
      uses: actions/setup-java@v1
      with:
        java-version: 1.10
    - name: Test with Gradle
      run: ./gradlew testCoverage detekt
